-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "imagePositionX" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "imagePositionY" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "imageScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
